from time import sleep


def changedmusiccontent(player):
    print("the music's blasting and undanceable")
    sleep(1)
    print("and all your friends are on the dance floor")
    print("")
    sleep(2)
    print("you start proyecting fake delight")
    sleep(1)
    print("you all start dancing for your lives")
    print("")
    sleep(3)
    print("the room is packed, ", end="")
    sleep(1)
    print("but no one listens")
    sleep(1)
    print("the crowd just stands, ", end="")
    sleep(1)
    print("there is no interest")
    print("")
    sleep(2)
    print("Except for y'all, ", end="")
    sleep(1)
    print("your little band")
    sleep(1)
    print("out of a dream, ", end="")
    sleep(1)
    print("the DJ snaps")
    print("")
    sleep(2)
    print("they see you vibing, ", end="")
    sleep(1)
    print("they want to please you")
    sleep(2)
    print("you keep pretending, ", end="")
    sleep(1)
    print("your dancing's vicious")
    print("")
    sleep(2)
    print("just a few minutes and a swift word")
    sleep(2)
    print("the music's changing, ", end="")
    sleep(2)
    print("your gambit works!")
    print("")
    sleep(2)
    player.party.change_music_great()
    player.memories.append("Changed Music")
    player.memories.remove("Gathering")
    return True
